-- Expression Transfer Script
-- Designed to work with meshes generated by Itseez3D's library
--
-- The lua script has access to the following new functions:
--      au(idx)         - Reads the weight/value of the given action unit from the template mesh.
--      rot_x()         - Reads the current rotation around the X axis (in degrees) of the template mesh.
--      rot_y()         - Reads the current rotation around the Y axis (in degrees) of the template mesh.
--      rot_z()         - Reads the current rotation around the Z axis (in degrees) of the template mesh.
--      set_bs(idx,w)   - Sets the given blendshape weight/value. The target will be the first node which has blendshapes.
--      set_rot(n,x,y,z)- Set an extra local rotation of the n-th node, with the specified rotation angles (in degrees)
--                        around the X, Y and Z axis.
--      eye_rot_x(eye)  - Reads the current rotation around the X axis (in degrees) of the given eye (0 or 1).
--      eye_rot_y(eye)  - Reads the current rotation around the Y axis (in degrees) of the given eye (0 or 1).

function clamp(n)
  if n < 0 then return 0 end
  if n > 1 then return 1 end
  return n
end

function clamprange(n, min, max)
 if n < min then return min end
 if n > max then return max end
 return n
end

nose_wrink = au(0)
jaw_x = au(4)
jaw_drop = clamprange(au(5), -0.9, 0.9)
lip_stretch = clamprange(au(7), -1.0, 1.0)
lip_corner_depr = au(8)
lip_presser = clamprange(au(9), -0.5, 0.5)

if jaw_drop < -0.05 then
  lip_corner_depr = lip_corner_depr - 2.0 * (jaw_drop + 0.05)
  jaw_drop = -0.05
end

-- Make the model appear more happy
lip_corner_depr = (lip_corner_depr - 0.2) * 1.5
lip_corner_depr = clamprange(lip_corner_depr, -1.0, 1.0)

if lip_stretch > 0 then
  set_bs(34, lip_stretch * 1.5)
  set_bs(35, lip_stretch * 1.5)
else
  set_bs(28, -lip_stretch * 1.5)
end

set_bs(33, au(6) * 0.5) -- upper_lip_raiser
set_bs(21, clamprange(jaw_x, 0.0, 0.8))
set_bs(23, clamprange(-jaw_x, 0.0, 0.8))
set_bs(22, jaw_drop)
set_bs(19, jaw_drop)
set_bs(36, lip_corner_depr)
set_bs(37, lip_corner_depr)
set_bs(43, nose_wrink * 0.5)
set_bs(25, lip_presser)
set_bs(31, lip_presser)

-- Candide-3 has wrong boundary here, it's between -0.02 for a fully open eye to 0 for a fully closed eye
left_eye = au(32) * 16
right_eye = au(33) * 16
-- clamp to reasonable values
left_eye = clamprange(left_eye, -0.16, 0.8)
right_eye = clamprange(right_eye, -0.16, 0.8)


-- Eye opening
set_bs(9, clamp(left_eye))
set_bs(11, clamp(-left_eye))
set_bs(10, clamp(right_eye))
set_bs(12, clamp(-right_eye))

-- Lower part of eyes
set_bs(5, clamp(au(34) * 20))
set_bs(6, clamp(au(35) * 20))

-- Rotate eyes (just a little bit, since it looks creepy)
set_bs(15, clamprange(eye_rot_x(0) * 0.02, -1.0, 1.0));
set_bs(16, clamprange(-eye_rot_y(0) * 0.04, -1.5, 1.5));

-- Candide-3 has wrong boundary here, it's between 0.00 -> ~0.05
set_bs(0, clamprange(au(50) * 20, -1, 1)) -- squeeze_l_eyebrow
set_bs(1, clamprange(au(51) * 20, -1, 1)) -- squeeze_r_eyebrow
set_bs(2, clamprange((au(44) + au(45)) * 10, -0.5, 1)) -- raise_l_i_eyebrow & raise_r_i_eyebrow
set_bs(3, clamprange((au(46) + au(48)) * 10, -0.5, 1)) -- raise_l_m_eyebrow & raise_l_o_eyebrow
set_bs(4, clamprange((au(47) + au(49)) * 10, -0.5, 1)) -- raise_r_m_eyebrow & raise_r_o_eyebrow

-- rotate head only
set_rot(0, rot_x(), rot_y(), rot_z())
